[workspace]
resolver = "2"
members = [
    "crates/kolom-lexer",
    "crates/kolom-syntax",
    "crates/kolom-sema",
    "crates/kolom-codegen",
    "crates/kolom-runtime",
    "crates/kolom-codegen-cranelift",
    "crates/kolom-interp",
    "crates/kolom-cli",
    "crates/kolom-lsp",
]

[profile.release]
lto = true
